name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 14

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build:prod

      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --non-interactive -P dev-aubinio --only hosting:dev-aubinio
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
